name: Auto Upload Energy Data

on:
  schedule:
    # 設定每 15 分鐘自動在雲端觸發一次程式
    - cron: '*/15 * * * *'
  workflow_dispatch: # 允許手動點擊執行測試

jobs:
  run-uploader:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run script
        run: python upload.py
